import React from 'react';
import { Share2, Printer, MapPin, RefreshCw, AlertTriangle, Info, Stethoscope } from 'lucide-react';
import ActionButtons from './ActionButtons';

const ResultPanel = ({ result, onReset }) => {
  const isHighRisk = result.riskLevel.toLowerCase() === 'high';

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 w-full max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col md:flex-row gap-6 mb-8 items-start">
        <div className="flex-1">
          <h2 className="text-2xl font-bold text-slate-900 mb-2 border-b border-slate-100 pb-3">Analysis Result</h2>
          
          <div className="mt-6 flex items-center gap-4">
            <div className={`p-4 rounded-2xl flex items-center justify-center ${
              isHighRisk ? 'bg-red-100 text-red-600' : 
              result.riskLevel.toLowerCase() === 'moderate' ? 'bg-amber-100 text-amber-600' : 
              'bg-emerald-100 text-emerald-600'
            }`}>
              <AlertTriangle size={32} />
            </div>
            <div>
              <div className="text-xs font-bold tracking-wider uppercase text-slate-500 mb-1">Risk Level</div>
              <div className={`text-xl font-bold ${
                isHighRisk ? 'text-red-700' : 
                result.riskLevel.toLowerCase() === 'moderate' ? 'text-amber-700' : 
                'text-emerald-700'
              }`}>{result.riskLevel}</div>
            </div>
          </div>
          
          <div className="mt-4 p-4 bg-slate-50 rounded-xl text-slate-700 italic border-l-4 border-slate-300">
            "{result.advisory}"
          </div>
        </div>
        
        <div className="flex-1 bg-blue-50 p-6 rounded-2xl border border-blue-100 w-full">
          <div className="text-xs font-bold tracking-wider uppercase text-blue-500 mb-1 flex items-center gap-1.5"><Info size={14}/> Predicted Condition</div>
          <div className="text-2xl font-bold text-blue-900 mb-2">{result.condition}</div>
          <div className="flex items-center gap-2 mb-4 text-sm font-medium">
            <span className="text-blue-700 bg-blue-100 px-2.5 py-1 rounded-full">{result.confidence} Confidence</span>
          </div>
          <p className="text-blue-800 text-sm leading-relaxed mb-4">
            {result.explanation}
          </p>
        </div>
      </div>
      
      <div className="my-6">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
          Recommended Actions
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pb-2">
          {result.actions?.map((action, i) => (
            <div key={i} className="flex items-start gap-3 bg-slate-50 border border-slate-100 p-4 rounded-xl">
              <div className="w-6 h-6 rounded-full bg-slate-200 text-slate-600 flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">{i+1}</div>
              <span className="text-slate-700 text-sm font-medium leading-tight pt-0.5">{action}</span>
            </div>
          ))}
        </div>
      </div>

      {result.recommendedSpecialist && (
        <div className="mt-6 p-5 bg-indigo-50 border border-indigo-100 rounded-2xl">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-indigo-100 rounded-lg text-indigo-600">
              <Stethoscope size={20} />
            </div>
            <h3 className="text-lg font-bold text-indigo-900">Recommended Specialist</h3>
          </div>
          <div className="ml-12">
            <div className="text-base font-bold text-indigo-800 mb-1">
              {result.recommendedSpecialist.type}
            </div>
            <div className="text-sm text-indigo-700 leading-relaxed">
              {result.recommendedSpecialist.reason}
            </div>
          </div>
        </div>
      )}

      <div className="mt-8 pt-4 pb-2 border-t border-slate-200">
        <div className="flex items-center gap-3 p-4 bg-amber-50 rounded-xl border border-amber-200">
          <AlertTriangle className="text-amber-500 shrink-0" size={24} />
          <p className="text-amber-800 text-sm">
            <strong>Important Disclaimer:</strong> This assessment is generated by artificial intelligence. It does not replace professional medical advice, diagnosis, or treatment. If you are experiencing a medical emergency, call emergency services immediately.
          </p>
        </div>
      </div>

      <ActionButtons onReset={onReset} result={result} />
    </div>
  );
};

export default ResultPanel;
